//! One schema definition for planning and materialized catalog rows.
//! Schema resolution never reads storage or constructs catalog data.

use super::{
    ColType, PG_AIOS_COLUMNS, PG_BACKEND_MEMORY_CONTEXTS_COLUMNS, PG_CONFIG_COLUMNS,
    PG_CURSORS_COLUMNS, PG_FILE_SETTINGS_COLUMNS, PG_HBA_FILE_RULES_COLUMNS,
    PG_IDENT_FILE_MAPPINGS_COLUMNS, PG_LOCKS_COLUMNS, PG_REPLICATION_ORIGIN_STATUS_COLUMNS,
    PG_REPLICATION_SLOTS_COLUMNS, PG_SHMEM_ALLOCATIONS_COLUMNS, PG_SHMEM_ALLOCATIONS_NUMA_COLUMNS,
    PG_STAT_ACTIVITY_COLUMNS, PG_STAT_ARCHIVER_COLUMNS, PG_STAT_BGWRITER_COLUMNS,
    PG_STAT_CHECKPOINTER_COLUMNS, PG_STAT_DATABASE_COLUMNS, PG_STAT_DATABASE_CONFLICTS_COLUMNS,
    PG_STAT_FUNCTIONS_COLUMNS, PG_STAT_GSSAPI_COLUMNS, PG_STAT_INDEXES_COLUMNS, PG_STAT_IO_COLUMNS,
    PG_STAT_PROGRESS_ANALYZE_COLUMNS, PG_STAT_PROGRESS_BASEBACKUP_COLUMNS,
    PG_STAT_PROGRESS_CLUSTER_COLUMNS, PG_STAT_PROGRESS_COPY_COLUMNS,
    PG_STAT_PROGRESS_CREATE_INDEX_COLUMNS, PG_STAT_PROGRESS_VACUUM_COLUMNS,
    PG_STAT_RECOVERY_PREFETCH_COLUMNS, PG_STAT_REPLICATION_COLUMNS,
    PG_STAT_REPLICATION_SLOTS_COLUMNS, PG_STAT_SLRU_COLUMNS, PG_STAT_SSL_COLUMNS,
    PG_STAT_SUBSCRIPTION_COLUMNS, PG_STAT_SUBSCRIPTION_STATS_COLUMNS, PG_STAT_TABLES_COLUMNS,
    PG_STAT_WAL_COLUMNS, PG_STAT_WAL_RECEIVER_COLUMNS, PG_STAT_XACT_TABLES_COLUMNS,
    PG_STATIO_INDEXES_COLUMNS, PG_STATIO_SEQUENCES_COLUMNS, PG_STATIO_TABLES_COLUMNS,
    PG_WAIT_EVENTS_COLUMNS, SynthDef,
};

pub(super) fn definition(name: &str, information_schema: bool) -> Option<SynthDef<'_>> {
    let columns: &[(&str, ColType)] = match (information_schema, name) {
        (false, "pg_transform") => &[
            ("tableoid", ColType::Oid),
            ("oid", ColType::Oid),
            ("trftype", ColType::Oid),
            ("trflang", ColType::Oid),
            ("trffromsql", ColType::Regproc),
            ("trftosql", ColType::Regproc),
        ],
        (false, "pg_seclabels") => &[
            ("objoid", ColType::Int4),
            ("classoid", ColType::Int4),
            ("objsubid", ColType::Int4),
            ("objtype", ColType::Text),
            ("objnamespace", ColType::Int4),
            ("objname", ColType::Text),
            ("provider", ColType::Text),
            ("label", ColType::Text),
        ],
        (false, "pg_shseclabel") => &[
            ("objoid", ColType::Int4),
            ("classoid", ColType::Int4),
            ("provider", ColType::Text),
            ("label", ColType::Text),
        ],
        (false, "pg_range") => &[
            ("rngtypid", ColType::Int4),
            ("rngsubtype", ColType::Int4),
            ("rngmultitypid", ColType::Int4),
        ],
        (false, "pg_foreign_data_wrapper") => &[
            ("tableoid", ColType::Int4),
            ("oid", ColType::Int4),
            ("fdwname", ColType::Name),
            ("fdwowner", ColType::Int4),
            ("fdwhandler", ColType::Int4),
            ("fdwvalidator", ColType::Int4),
            (
                "fdwacl",
                ColType::Array(crate::sql::types::ArrElem::AclItem),
            ),
            (
                "fdwoptions",
                ColType::Array(crate::sql::types::ArrElem::Text),
            ),
        ],
        (false, "pg_foreign_server") => &[
            ("tableoid", ColType::Int4),
            ("oid", ColType::Int4),
            ("srvname", ColType::Name),
            ("srvowner", ColType::Int4),
            ("srvfdw", ColType::Int4),
            ("srvtype", ColType::Text),
            ("srvversion", ColType::Text),
            (
                "srvacl",
                ColType::Array(crate::sql::types::ArrElem::AclItem),
            ),
            (
                "srvoptions",
                ColType::Array(crate::sql::types::ArrElem::Text),
            ),
        ],
        (false, "pg_foreign_table") => &[
            ("ftrelid", ColType::Int4),
            ("ftserver", ColType::Int4),
            (
                "ftoptions",
                ColType::Array(crate::sql::types::ArrElem::Text),
            ),
        ],
        (false, "pg_user_mapping") => &[
            ("oid", ColType::Int4),
            ("umuser", ColType::Int4),
            ("umserver", ColType::Int4),
            (
                "umoptions",
                ColType::Array(crate::sql::types::ArrElem::Text),
            ),
        ],
        (false, "pg_user_mappings") => &[
            ("umid", ColType::Int4),
            ("srvid", ColType::Int4),
            ("srvname", ColType::Name),
            ("umuser", ColType::Int4),
            ("usename", ColType::Name),
            (
                "umoptions",
                ColType::Array(crate::sql::types::ArrElem::Text),
            ),
        ],
        (false, "pg_init_privs") => &[
            ("objoid", ColType::Int4),
            ("classoid", ColType::Int4),
            ("objsubid", ColType::Int4),
            ("privtype", ColType::Bpchar),
            (
                "initprivs",
                ColType::Array(crate::sql::types::ArrElem::AclItem),
            ),
        ],
        (false, "pg_largeobject_metadata") => &[
            ("oid", ColType::Oid),
            ("lomowner", ColType::Oid),
            (
                "lomacl",
                ColType::Array(crate::sql::types::ArrElem::AclItem),
            ),
        ],
        (false, "pg_largeobject") => &[
            ("loid", ColType::Oid),
            ("pageno", ColType::Int4),
            ("data", ColType::Bytea),
        ],
        (false, "pg_parameter_acl") => &[
            ("parname", ColType::Text),
            (
                "paracl",
                ColType::Array(crate::sql::types::ArrElem::AclItem),
            ),
        ],
        (false, "pg_default_acl") => &[
            ("oid", ColType::Int4),
            ("tableoid", ColType::Int4),
            ("defaclrole", ColType::Int4),
            ("defaclnamespace", ColType::Int4),
            ("defaclobjtype", ColType::Bpchar),
            (
                "defaclacl",
                ColType::Array(crate::sql::types::ArrElem::AclItem),
            ),
        ],
        (false, "pg_description") => &[
            ("objoid", ColType::Oid),
            ("classoid", ColType::Oid),
            ("objsubid", ColType::Int4),
            ("description", ColType::Text),
        ],
        (false, "pg_shdescription") => &[
            ("objoid", ColType::Int4),
            ("classoid", ColType::Int4),
            ("description", ColType::Text),
        ],
        (false, "pg_stats") => &[
            ("schemaname", ColType::Name),
            ("tablename", ColType::Name),
            ("attname", ColType::Name),
            ("inherited", ColType::Bool),
            ("null_frac", ColType::Float4),
            ("avg_width", ColType::Int4),
            ("n_distinct", ColType::Float4),
            ("most_common_vals", ColType::AnyArray),
            (
                "most_common_freqs",
                ColType::Array(crate::sql::types::ArrElem::Float4),
            ),
            ("histogram_bounds", ColType::AnyArray),
            ("correlation", ColType::Float4),
            ("most_common_elems", ColType::AnyArray),
            (
                "most_common_elem_freqs",
                ColType::Array(crate::sql::types::ArrElem::Float4),
            ),
            (
                "elem_count_histogram",
                ColType::Array(crate::sql::types::ArrElem::Float4),
            ),
            ("range_length_histogram", ColType::AnyArray),
            ("range_empty_frac", ColType::Float4),
            ("range_bounds_histogram", ColType::AnyArray),
        ],
        (false, "pg_statistic_ext") => &[
            ("tableoid", ColType::Int4),
            ("oid", ColType::Int4),
            ("stxrelid", ColType::Int4),
            ("stxname", ColType::Name),
            ("stxnamespace", ColType::Int4),
            ("stxowner", ColType::Int4),
            ("stxkeys", ColType::Int2Vector),
            ("stxstattarget", ColType::Int2),
            ("stxkind", ColType::Array(crate::sql::types::ArrElem::Char)),
            ("stxexprs", ColType::PgNodeTree),
        ],
        (false, "pg_statistic_ext_data") => &[
            ("tableoid", ColType::Int4),
            ("stxoid", ColType::Int4),
            ("stxdinherit", ColType::Bool),
            ("stxdndistinct", ColType::PgNdistinct),
            ("stxddependencies", ColType::PgDependencies),
            ("stxdmcv", ColType::PgMcvList),
            ("stxdexpr", ColType::PgStatisticArray),
        ],
        (false, "pg_stats_ext") => &[
            ("schemaname", ColType::Name),
            ("tablename", ColType::Name),
            ("statistics_schemaname", ColType::Name),
            ("statistics_name", ColType::Name),
            ("statistics_owner", ColType::Name),
            ("attnames", ColType::Array(crate::sql::types::ArrElem::Name)),
            ("exprs", ColType::Array(crate::sql::types::ArrElem::Text)),
            ("kinds", ColType::Array(crate::sql::types::ArrElem::Char)),
            ("inherited", ColType::Bool),
            ("n_distinct", ColType::PgNdistinct),
            ("dependencies", ColType::PgDependencies),
            (
                "most_common_vals",
                ColType::Array(crate::sql::types::ArrElem::Text),
            ),
            (
                "most_common_val_nulls",
                ColType::Array(crate::sql::types::ArrElem::Bool),
            ),
            (
                "most_common_freqs",
                ColType::Array(crate::sql::types::ArrElem::Float8),
            ),
            (
                "most_common_base_freqs",
                ColType::Array(crate::sql::types::ArrElem::Float8),
            ),
        ],
        (false, "pg_stats_ext_exprs") => &[
            ("schemaname", ColType::Name),
            ("tablename", ColType::Name),
            ("statistics_schemaname", ColType::Name),
            ("statistics_name", ColType::Name),
            ("statistics_owner", ColType::Name),
            ("expr", ColType::Text),
            ("inherited", ColType::Bool),
            ("null_frac", ColType::Float4),
            ("avg_width", ColType::Int4),
            ("n_distinct", ColType::Float4),
            ("most_common_vals", ColType::AnyArray),
            (
                "most_common_freqs",
                ColType::Array(crate::sql::types::ArrElem::Float4),
            ),
            ("histogram_bounds", ColType::AnyArray),
            ("correlation", ColType::Float4),
            ("most_common_elems", ColType::AnyArray),
            (
                "most_common_elem_freqs",
                ColType::Array(crate::sql::types::ArrElem::Float4),
            ),
            (
                "elem_count_histogram",
                ColType::Array(crate::sql::types::ArrElem::Float4),
            ),
        ],
        (false, "pg_policy") => &[
            ("tableoid", ColType::Int4),
            ("oid", ColType::Int4),
            ("polname", ColType::Name),
            ("polrelid", ColType::Int4),
            ("polcmd", ColType::Bpchar),
            ("polpermissive", ColType::Bool),
            ("polroles", ColType::Array(crate::sql::types::ArrElem::Oid)),
            ("polqual", ColType::PgNodeTree),
            ("polwithcheck", ColType::PgNodeTree),
        ],
        (false, "pg_policies") => &[
            ("schemaname", ColType::Name),
            ("tablename", ColType::Name),
            ("policyname", ColType::Name),
            ("permissive", ColType::Text),
            ("roles", ColType::Array(crate::sql::types::ArrElem::Name)),
            ("cmd", ColType::Text),
            ("qual", ColType::Text),
            ("with_check", ColType::Text),
        ],
        (false, "pg_publication") => &[
            ("tableoid", ColType::Int4),
            ("oid", ColType::Int4),
            ("pubname", ColType::Text),
            ("pubowner", ColType::Int4),
            ("puballtables", ColType::Bool),
            ("pubinsert", ColType::Bool),
            ("pubupdate", ColType::Bool),
            ("pubdelete", ColType::Bool),
            ("pubtruncate", ColType::Bool),
            ("pubviaroot", ColType::Bool),
            ("pubgencols", ColType::Bpchar),
        ],
        (false, "pg_publication_namespace") => &[
            ("tableoid", ColType::Int4),
            ("oid", ColType::Int4),
            ("pnpubid", ColType::Int4),
            ("pnnspid", ColType::Int4),
        ],
        (false, "pg_publication_rel") => &[
            ("tableoid", ColType::Int4),
            ("oid", ColType::Int4),
            ("prpubid", ColType::Int4),
            ("prrelid", ColType::Int4),
            ("prqual", ColType::Text),
            ("prattrs", ColType::Int2Vector),
        ],
        (false, "pg_publication_tables") => &[
            ("pubname", ColType::Name),
            ("schemaname", ColType::Name),
            ("tablename", ColType::Name),
            ("attnames", ColType::Array(crate::sql::types::ArrElem::Name)),
            ("rowfilter", ColType::Text),
        ],
        (false, "pg_replication_slots") => PG_REPLICATION_SLOTS_COLUMNS,
        (false, "pg_replication_origin") => &[("roident", ColType::Oid), ("roname", ColType::Text)],
        (false, "pg_replication_origin_status") => PG_REPLICATION_ORIGIN_STATUS_COLUMNS,
        (false, "pg_stat_replication") => PG_STAT_REPLICATION_COLUMNS,
        (false, "pg_stat_replication_slots") => PG_STAT_REPLICATION_SLOTS_COLUMNS,
        (false, "pg_subscription") => &[
            ("tableoid", ColType::Int4),
            ("oid", ColType::Int4),
            ("subdbid", ColType::Int4),
            ("subskiplsn", ColType::Text),
            ("subname", ColType::Name),
            ("subowner", ColType::Int4),
            ("subenabled", ColType::Bool),
            ("subbinary", ColType::Bool),
            ("substream", ColType::Bpchar),
            ("subtwophasestate", ColType::Bpchar),
            ("subdisableonerr", ColType::Bool),
            ("subpasswordrequired", ColType::Bool),
            ("subrunasowner", ColType::Bool),
            ("subfailover", ColType::Bool),
            ("subconninfo", ColType::Text),
            ("subslotname", ColType::Name),
            ("subsynccommit", ColType::Text),
            (
                "subpublications",
                ColType::Array(crate::sql::types::ArrElem::Text),
            ),
            ("suborigin", ColType::Text),
        ],
        (false, "pg_subscription_rel") => &[
            ("srsubid", ColType::Int4),
            ("srrelid", ColType::Int4),
            ("srsubstate", ColType::Bpchar),
            ("srsublsn", ColType::Text),
        ],
        (false, "pg_stat_subscription") => PG_STAT_SUBSCRIPTION_COLUMNS,
        (false, "pg_stat_subscription_stats") => PG_STAT_SUBSCRIPTION_STATS_COLUMNS,
        (false, "pg_inherits") => &[
            ("inhrelid", ColType::Int4),
            ("inhparent", ColType::Int4),
            ("inhseqno", ColType::Int4),
            ("inhdetachpending", ColType::Bool),
        ],
        (false, "pg_partitioned_table") => &[
            ("partrelid", ColType::Int4),
            ("partstrat", ColType::Char),
            ("partnatts", ColType::Int2),
            ("partdefid", ColType::Int4),
            ("partattrs", ColType::Int2Vector),
            ("partclass", ColType::OidVector),
            ("partcollation", ColType::OidVector),
            ("partexprs", ColType::PgNodeTree),
        ],
        (false, "pg_class") => &[
            ("oid", ColType::Oid),
            ("relname", ColType::Name),
            ("relnamespace", ColType::Oid),
            ("reltype", ColType::Oid),
            ("reloftype", ColType::Oid),
            ("relowner", ColType::Oid),
            ("relam", ColType::Oid),
            ("relfilenode", ColType::Oid),
            ("reltablespace", ColType::Oid),
            ("relpages", ColType::Int4),
            ("reltuples", ColType::Float4),
            ("relallvisible", ColType::Int4),
            ("relallfrozen", ColType::Int4),
            ("reltoastrelid", ColType::Oid),
            ("relhasindex", ColType::Bool),
            ("relisshared", ColType::Bool),
            ("relpersistence", ColType::Char),
            ("relkind", ColType::Char),
            ("relnatts", ColType::Int2),
            ("relchecks", ColType::Int2),
            ("relhasrules", ColType::Bool),
            ("relhastriggers", ColType::Bool),
            ("relhassubclass", ColType::Bool),
            ("relrowsecurity", ColType::Bool),
            ("relforcerowsecurity", ColType::Bool),
            ("relispopulated", ColType::Bool),
            ("relreplident", ColType::Char),
            ("relispartition", ColType::Bool),
            ("relrewrite", ColType::Oid),
            ("relfrozenxid", ColType::Xid),
            ("relminmxid", ColType::Xid),
            (
                "relacl",
                ColType::Array(crate::sql::types::ArrElem::AclItem),
            ),
            (
                "reloptions",
                ColType::Array(crate::sql::types::ArrElem::Text),
            ),
            ("relpartbound", ColType::PgNodeTree),
        ],
        (false, "pg_tablespace") => &[
            ("tableoid", ColType::Int4),
            ("oid", ColType::Int4),
            ("spcname", ColType::Name),
            ("spcowner", ColType::Int4),
            (
                "spcacl",
                ColType::Array(crate::sql::types::ArrElem::AclItem),
            ),
            (
                "spcoptions",
                ColType::Array(crate::sql::types::ArrElem::Text),
            ),
        ],
        (false, "pg_constraint") => &[
            ("oid", ColType::Oid),
            ("conname", ColType::Name),
            ("connamespace", ColType::Oid),
            ("contype", ColType::Char),
            ("condeferrable", ColType::Bool),
            ("condeferred", ColType::Bool),
            ("conenforced", ColType::Bool),
            ("convalidated", ColType::Bool),
            ("conrelid", ColType::Oid),
            ("contypid", ColType::Oid),
            ("conindid", ColType::Oid),
            ("conparentid", ColType::Oid),
            ("confrelid", ColType::Oid),
            ("confupdtype", ColType::Char),
            ("confdeltype", ColType::Char),
            ("confmatchtype", ColType::Char),
            ("conislocal", ColType::Bool),
            ("coninhcount", ColType::Int2),
            ("connoinherit", ColType::Bool),
            ("conperiod", ColType::Bool),
            ("conkey", ColType::Array(crate::sql::types::ArrElem::Int2)),
            ("confkey", ColType::Array(crate::sql::types::ArrElem::Int2)),
            ("conpfeqop", ColType::Array(crate::sql::types::ArrElem::Oid)),
            ("conppeqop", ColType::Array(crate::sql::types::ArrElem::Oid)),
            ("conffeqop", ColType::Array(crate::sql::types::ArrElem::Oid)),
            (
                "confdelsetcols",
                ColType::Array(crate::sql::types::ArrElem::Int2),
            ),
            ("conexclop", ColType::Array(crate::sql::types::ArrElem::Oid)),
            ("conbin", ColType::PgNodeTree),
        ],
        (false, "pg_rewrite") => &[
            ("tableoid", ColType::Int4),
            ("oid", ColType::Int4),
            ("rulename", ColType::Text),
            ("ev_class", ColType::Int4),
            ("ev_type", ColType::Bpchar),
            ("ev_enabled", ColType::Bpchar),
            ("is_instead", ColType::Bool),
        ],
        (false, "pg_available_extensions") => &[
            ("name", ColType::Name),
            ("default_version", ColType::Text),
            ("installed_version", ColType::Text),
            ("comment", ColType::Text),
        ],
        (false, "pg_available_extension_versions") => &[
            ("name", ColType::Name),
            ("version", ColType::Text),
            ("installed", ColType::Bool),
            ("superuser", ColType::Bool),
            ("trusted", ColType::Bool),
            ("relocatable", ColType::Bool),
            ("schema", ColType::Name),
            ("requires", ColType::Array(crate::sql::types::ArrElem::Name)),
            ("comment", ColType::Text),
        ],
        (false, "pg_extension") => &[
            ("tableoid", ColType::Int4),
            ("oid", ColType::Int4),
            ("extname", ColType::Name),
            ("extowner", ColType::Int4),
            ("extnamespace", ColType::Int4),
            ("extrelocatable", ColType::Bool),
            ("extversion", ColType::Text),
            ("extconfig", ColType::Array(crate::sql::types::ArrElem::Oid)),
            (
                "extcondition",
                ColType::Array(crate::sql::types::ArrElem::Text),
            ),
        ],
        (false, "pg_depend") => &[
            ("classid", ColType::Oid),
            ("objid", ColType::Oid),
            ("objsubid", ColType::Int4),
            ("refclassid", ColType::Oid),
            ("refobjid", ColType::Oid),
            ("refobjsubid", ColType::Int4),
            ("deptype", ColType::Bpchar),
        ],
        (false, "pg_index") => &[
            ("indexrelid", ColType::Int4),
            ("indrelid", ColType::Int4),
            ("indisprimary", ColType::Bool),
            ("indisunique", ColType::Bool),
            ("indisclustered", ColType::Bool),
            ("indischeckxmin", ColType::Bool),
            ("indisvalid", ColType::Bool),
            ("indimmediate", ColType::Bool),
            ("indisreplident", ColType::Bool),
            ("indnullsnotdistinct", ColType::Bool),
            ("indnatts", ColType::Int4),
            ("indnkeyatts", ColType::Int4),
            ("indkey", ColType::Int2Vector),
            (
                "indoption",
                ColType::Array(crate::sql::types::ArrElem::Int4),
            ),
            ("indpred", ColType::Text),
            ("indisready", ColType::Bool),
            ("indislive", ColType::Bool),
            ("indexprs", ColType::Text),
            (
                "indcollation",
                ColType::Array(crate::sql::types::ArrElem::Int4),
            ),
            ("indclass", ColType::OidVector),
        ],
        (false, "pg_attribute") => &[
            ("attrelid", ColType::Oid),
            ("attname", ColType::Name),
            ("atttypid", ColType::Oid),
            ("attlen", ColType::Int2),
            ("attnum", ColType::Int2),
            ("atttypmod", ColType::Int4),
            ("attndims", ColType::Int2),
            ("attbyval", ColType::Bool),
            ("attalign", ColType::Char),
            ("attstorage", ColType::Char),
            ("attcompression", ColType::Char),
            ("attnotnull", ColType::Bool),
            ("atthasdef", ColType::Bool),
            ("atthasmissing", ColType::Bool),
            ("attidentity", ColType::Char),
            ("attgenerated", ColType::Char),
            ("attisdropped", ColType::Bool),
            ("attislocal", ColType::Bool),
            ("attinhcount", ColType::Int2),
            ("attcollation", ColType::Oid),
            ("attstattarget", ColType::Int2),
            (
                "attacl",
                ColType::Array(crate::sql::types::ArrElem::AclItem),
            ),
            (
                "attoptions",
                ColType::Array(crate::sql::types::ArrElem::Text),
            ),
            (
                "attfdwoptions",
                ColType::Array(crate::sql::types::ArrElem::Text),
            ),
            ("attmissingval", ColType::Text),
        ],
        (false, "pg_attrdef") => &[
            ("oid", ColType::Oid),
            ("adrelid", ColType::Oid),
            ("adnum", ColType::Int2),
            ("adbin", ColType::PgNodeTree),
        ],
        (false, "pg_cast") => &[
            ("tableoid", ColType::Oid),
            ("oid", ColType::Oid),
            ("castsource", ColType::Oid),
            ("casttarget", ColType::Oid),
            ("castfunc", ColType::Oid),
            ("castcontext", ColType::Bpchar),
            ("castmethod", ColType::Bpchar),
        ],
        (false, "pg_operator") => &[
            ("tableoid", ColType::Oid),
            ("oid", ColType::Oid),
            ("oprname", ColType::Name),
            ("oprnamespace", ColType::Oid),
            ("oprowner", ColType::Oid),
            ("oprkind", ColType::Bpchar),
            ("oprcanmerge", ColType::Bool),
            ("oprcanhash", ColType::Bool),
            ("oprleft", ColType::Oid),
            ("oprright", ColType::Oid),
            ("oprresult", ColType::Oid),
            ("oprcom", ColType::Oid),
            ("oprnegate", ColType::Oid),
            ("oprcode", ColType::Regproc),
            ("oprrest", ColType::Regproc),
            ("oprjoin", ColType::Regproc),
        ],
        (false, "pg_opfamily") => &[
            ("tableoid", ColType::Oid),
            ("oid", ColType::Oid),
            ("opfmethod", ColType::Oid),
            ("opfname", ColType::Name),
            ("opfnamespace", ColType::Oid),
            ("opfowner", ColType::Oid),
        ],
        (false, "pg_opclass") => &[
            ("tableoid", ColType::Oid),
            ("oid", ColType::Oid),
            ("opcmethod", ColType::Oid),
            ("opcname", ColType::Name),
            ("opcnamespace", ColType::Oid),
            ("opcowner", ColType::Oid),
            ("opcfamily", ColType::Oid),
            ("opcintype", ColType::Oid),
            ("opcdefault", ColType::Bool),
            ("opckeytype", ColType::Oid),
        ],
        (false, "pg_amop") => &[
            ("tableoid", ColType::Oid),
            ("oid", ColType::Oid),
            ("amopfamily", ColType::Oid),
            ("amoplefttype", ColType::Oid),
            ("amoprighttype", ColType::Oid),
            ("amopstrategy", ColType::Int2),
            ("amoppurpose", ColType::Bpchar),
            ("amopopr", ColType::Oid),
            ("amopmethod", ColType::Oid),
            ("amopsortfamily", ColType::Oid),
        ],
        (false, "pg_amproc") => &[
            ("tableoid", ColType::Oid),
            ("oid", ColType::Oid),
            ("amprocfamily", ColType::Oid),
            ("amproclefttype", ColType::Oid),
            ("amprocrighttype", ColType::Oid),
            ("amprocnum", ColType::Int2),
            ("amproc", ColType::Regproc),
        ],
        (false, "pg_trigger") => &[
            ("tableoid", ColType::Oid),
            ("oid", ColType::Oid),
            ("tgrelid", ColType::Oid),
            ("tgparentid", ColType::Oid),
            ("tgname", ColType::Name),
            ("tgfoid", ColType::Oid),
            ("tgtype", ColType::Int2),
            ("tgenabled", ColType::Bpchar),
            ("tgisinternal", ColType::Bool),
            ("tgconstrrelid", ColType::Oid),
            ("tgconstrindid", ColType::Oid),
            ("tgconstraint", ColType::Oid),
            ("tgdeferrable", ColType::Bool),
            ("tginitdeferred", ColType::Bool),
            ("tgnargs", ColType::Int2),
            ("tgattr", ColType::Int2Vector),
            ("tgargs", ColType::Bytea),
            ("tgqual", ColType::Text),
            ("tgoldtable", ColType::Name),
            ("tgnewtable", ColType::Name),
        ],
        (false, "pg_event_trigger") => &[
            ("tableoid", ColType::Oid),
            ("oid", ColType::Oid),
            ("evtname", ColType::Name),
            ("evtevent", ColType::Name),
            ("evtowner", ColType::Oid),
            ("evtfoid", ColType::Oid),
            ("evtenabled", ColType::Bpchar),
            ("evttags", ColType::Array(crate::sql::types::ArrElem::Text)),
        ],
        (false, "pg_am") => &[
            ("tableoid", ColType::Oid),
            ("oid", ColType::Oid),
            ("amname", ColType::Name),
            ("amhandler", ColType::Regproc),
            ("amtype", ColType::Char),
        ],
        (false, "pg_language") => &[
            ("tableoid", ColType::Int4),
            ("oid", ColType::Int4),
            ("lanname", ColType::Name),
            ("lanowner", ColType::Int4),
            ("lanpltrusted", ColType::Bool),
            ("lanispl", ColType::Bool),
            ("lanplcallfoid", ColType::Int4),
            ("lanvalidator", ColType::Int4),
            ("laninline", ColType::Int4),
            (
                "lanacl",
                ColType::Array(crate::sql::types::ArrElem::AclItem),
            ),
        ],
        (false, "pg_proc") => &[
            ("tableoid", ColType::Oid),
            ("oid", ColType::Oid),
            ("proname", ColType::Name),
            ("pronamespace", ColType::Oid),
            ("pronargs", ColType::Int4),
            ("prorettype", ColType::Oid),
            ("proretset", ColType::Bool),
            ("prokind", ColType::Bpchar),
            ("proargtypes", ColType::OidVector),
            ("provolatile", ColType::Bpchar),
            ("proparallel", ColType::Bpchar),
            ("proowner", ColType::Oid),
            ("prosecdef", ColType::Bool),
            (
                "proacl",
                ColType::Array(crate::sql::types::ArrElem::AclItem),
            ),
            ("prolang", ColType::Oid),
            ("prosrc", ColType::Text),
            ("probin", ColType::Text),
            ("proisstrict", ColType::Bool),
            ("proleakproof", ColType::Bool),
            (
                "proconfig",
                ColType::Array(crate::sql::types::ArrElem::Text),
            ),
            ("procost", ColType::Float8),
            ("prorows", ColType::Float8),
            (
                "protrftypes",
                ColType::Array(crate::sql::types::ArrElem::Oid),
            ),
            ("prosupport", ColType::Regproc),
            ("pronargdefaults", ColType::Int4),
            ("provariadic", ColType::Oid),
            (
                "proallargtypes",
                ColType::Array(crate::sql::types::ArrElem::Oid),
            ),
            (
                "proargmodes",
                ColType::Array(crate::sql::types::ArrElem::Char),
            ),
            (
                "proargnames",
                ColType::Array(crate::sql::types::ArrElem::Text),
            ),
            ("proargdefaults", ColType::PgNodeTree),
            ("prosqlbody", ColType::PgNodeTree),
        ],
        (false, "pg_aggregate") => &[
            ("aggfnoid", ColType::Regproc),
            ("aggkind", ColType::Bpchar),
            ("aggnumdirectargs", ColType::Int2),
            ("aggtransfn", ColType::Regproc),
            ("aggfinalfn", ColType::Regproc),
            ("aggcombinefn", ColType::Regproc),
            ("aggserialfn", ColType::Regproc),
            ("aggdeserialfn", ColType::Regproc),
            ("aggmtransfn", ColType::Regproc),
            ("aggminvtransfn", ColType::Regproc),
            ("aggmfinalfn", ColType::Regproc),
            ("aggfinalextra", ColType::Bool),
            ("aggmfinalextra", ColType::Bool),
            ("aggfinalmodify", ColType::Bpchar),
            ("aggmfinalmodify", ColType::Bpchar),
            ("aggsortop", ColType::Oid),
            ("aggtranstype", ColType::Oid),
            ("aggtransspace", ColType::Int4),
            ("aggmtranstype", ColType::Oid),
            ("aggmtransspace", ColType::Int4),
            ("agginitval", ColType::Text),
            ("aggminitval", ColType::Text),
        ],
        (false, "pg_ts_parser") => &[
            ("tableoid", ColType::Oid),
            ("oid", ColType::Oid),
            ("prsname", ColType::Name),
            ("prsnamespace", ColType::Oid),
            ("prsstart", ColType::Regproc),
            ("prstoken", ColType::Regproc),
            ("prsend", ColType::Regproc),
            ("prsheadline", ColType::Regproc),
            ("prslextype", ColType::Regproc),
        ],
        (false, "pg_ts_template") => &[
            ("tableoid", ColType::Oid),
            ("oid", ColType::Oid),
            ("tmplname", ColType::Name),
            ("tmplnamespace", ColType::Oid),
            ("tmplinit", ColType::Regproc),
            ("tmpllexize", ColType::Regproc),
        ],
        (false, "pg_ts_dict") => &[
            ("tableoid", ColType::Oid),
            ("oid", ColType::Oid),
            ("dictname", ColType::Name),
            ("dictnamespace", ColType::Oid),
            ("dictowner", ColType::Oid),
            ("dicttemplate", ColType::Oid),
            ("dictinitoption", ColType::Text),
        ],
        (false, "pg_ts_config") => &[
            ("tableoid", ColType::Oid),
            ("oid", ColType::Oid),
            ("cfgname", ColType::Name),
            ("cfgnamespace", ColType::Oid),
            ("cfgowner", ColType::Oid),
            ("cfgparser", ColType::Oid),
        ],
        (false, "pg_ts_config_map") => &[
            ("mapcfg", ColType::Oid),
            ("maptokentype", ColType::Int4),
            ("mapseqno", ColType::Int4),
            ("mapdict", ColType::Oid),
        ],
        (false, "pg_collation") => &[
            ("tableoid", ColType::Oid),
            ("oid", ColType::Oid),
            ("collname", ColType::Name),
            ("collnamespace", ColType::Oid),
            ("collowner", ColType::Oid),
            ("collprovider", ColType::Bpchar),
            ("collisdeterministic", ColType::Bool),
            ("collencoding", ColType::Int4),
            ("collcollate", ColType::Text),
            ("collctype", ColType::Text),
            ("colllocale", ColType::Text),
            ("collicurules", ColType::Text),
            ("collversion", ColType::Text),
        ],
        (false, "pg_conversion") => &[
            ("tableoid", ColType::Int4),
            ("oid", ColType::Int4),
            ("conname", ColType::Name),
            ("connamespace", ColType::Int4),
            ("conowner", ColType::Int4),
            ("conforencoding", ColType::Int4),
            ("contoencoding", ColType::Int4),
            ("conproc", ColType::Regproc),
            ("condefault", ColType::Bool),
        ],
        (false, "pg_enum") => &[
            ("oid", ColType::Int4),
            ("enumtypid", ColType::Int4),
            ("enumsortorder", ColType::Float8),
            ("enumlabel", ColType::Text),
        ],
        (false, "pg_locks") => PG_LOCKS_COLUMNS,
        (false, "pg_stat_activity") => PG_STAT_ACTIVITY_COLUMNS,
        (false, "pg_stat_ssl") => PG_STAT_SSL_COLUMNS,
        (false, "pg_stat_all_tables" | "pg_stat_sys_tables" | "pg_stat_user_tables") => {
            PG_STAT_TABLES_COLUMNS
        }
        (
            false,
            "pg_stat_xact_all_tables" | "pg_stat_xact_sys_tables" | "pg_stat_xact_user_tables",
        ) => PG_STAT_XACT_TABLES_COLUMNS,
        (false, "pg_stat_all_indexes" | "pg_stat_sys_indexes" | "pg_stat_user_indexes") => {
            PG_STAT_INDEXES_COLUMNS
        }
        (false, "pg_aios") => PG_AIOS_COLUMNS,
        (false, "pg_backend_memory_contexts") => PG_BACKEND_MEMORY_CONTEXTS_COLUMNS,
        (false, "pg_config") => PG_CONFIG_COLUMNS,
        (false, "pg_file_settings") => PG_FILE_SETTINGS_COLUMNS,
        (false, "pg_hba_file_rules") => PG_HBA_FILE_RULES_COLUMNS,
        (false, "pg_ident_file_mappings") => PG_IDENT_FILE_MAPPINGS_COLUMNS,
        (false, "pg_shmem_allocations") => PG_SHMEM_ALLOCATIONS_COLUMNS,
        (false, "pg_shmem_allocations_numa") => PG_SHMEM_ALLOCATIONS_NUMA_COLUMNS,
        (false, "pg_stat_wal_receiver") => PG_STAT_WAL_RECEIVER_COLUMNS,
        (false, "pg_stat_progress_analyze") => PG_STAT_PROGRESS_ANALYZE_COLUMNS,
        (false, "pg_stat_progress_vacuum") => PG_STAT_PROGRESS_VACUUM_COLUMNS,
        (false, "pg_stat_progress_cluster") => PG_STAT_PROGRESS_CLUSTER_COLUMNS,
        (false, "pg_stat_progress_create_index") => PG_STAT_PROGRESS_CREATE_INDEX_COLUMNS,
        (false, "pg_stat_progress_basebackup") => PG_STAT_PROGRESS_BASEBACKUP_COLUMNS,
        (false, "pg_stat_progress_copy") => PG_STAT_PROGRESS_COPY_COLUMNS,
        (false, "pg_statio_all_tables" | "pg_statio_sys_tables" | "pg_statio_user_tables") => {
            PG_STATIO_TABLES_COLUMNS
        }
        (false, "pg_statio_all_indexes" | "pg_statio_sys_indexes" | "pg_statio_user_indexes") => {
            PG_STATIO_INDEXES_COLUMNS
        }
        (
            false,
            "pg_statio_all_sequences" | "pg_statio_sys_sequences" | "pg_statio_user_sequences",
        ) => PG_STATIO_SEQUENCES_COLUMNS,
        (false, "pg_stat_slru") => PG_STAT_SLRU_COLUMNS,
        (false, "pg_stat_recovery_prefetch") => PG_STAT_RECOVERY_PREFETCH_COLUMNS,
        (false, "pg_stat_gssapi") => PG_STAT_GSSAPI_COLUMNS,
        (false, "pg_stat_user_functions" | "pg_stat_xact_user_functions") => {
            PG_STAT_FUNCTIONS_COLUMNS
        }
        (false, "pg_stat_archiver") => PG_STAT_ARCHIVER_COLUMNS,
        (false, "pg_stat_bgwriter") => PG_STAT_BGWRITER_COLUMNS,
        (false, "pg_stat_checkpointer") => PG_STAT_CHECKPOINTER_COLUMNS,
        (false, "pg_stat_io") => PG_STAT_IO_COLUMNS,
        (false, "pg_stat_wal") => PG_STAT_WAL_COLUMNS,
        (false, "pg_stat_database") => PG_STAT_DATABASE_COLUMNS,
        (false, "pg_stat_database_conflicts") => PG_STAT_DATABASE_CONFLICTS_COLUMNS,
        (false, "pg_cursors") => PG_CURSORS_COLUMNS,
        (false, "pg_prepared_statements") => &[
            ("name", ColType::Text),
            ("statement", ColType::Text),
            ("prepare_time", ColType::Timestamptz),
            (
                "parameter_types",
                ColType::Array(crate::sql::types::ArrElem::Regtype),
            ),
            (
                "result_types",
                ColType::Array(crate::sql::types::ArrElem::Regtype),
            ),
            ("from_sql", ColType::Bool),
            ("generic_plans", ColType::Int8),
            ("custom_plans", ColType::Int8),
        ],
        (false, "pg_wait_events") => PG_WAIT_EVENTS_COLUMNS,
        (false, "pg_shdepend") => &[
            ("dbid", ColType::Oid),
            ("classid", ColType::Oid),
            ("objid", ColType::Oid),
            ("objsubid", ColType::Int4),
            ("refclassid", ColType::Oid),
            ("refobjid", ColType::Oid),
            ("deptype", ColType::Char),
        ],
        (false, "pg_timezone_names") => &[
            ("name", ColType::Text),
            ("abbrev", ColType::Text),
            ("utc_offset", ColType::Interval),
            ("is_dst", ColType::Bool),
        ],
        (false, "pg_timezone_abbrevs") => &[
            ("abbrev", ColType::Text),
            ("utc_offset", ColType::Interval),
            ("is_dst", ColType::Bool),
        ],
        (false, "pg_type") => &[
            ("oid", ColType::Int4),
            ("typname", ColType::Name),
            ("typlen", ColType::Int4),
            ("typcollation", ColType::Int4),
            ("typnamespace", ColType::Int4),
            ("typtype", ColType::Bpchar), // 'b' = base type
            ("typcategory", ColType::Bpchar),
            ("typbasetype", ColType::Int4), // 0 unless a domain
            ("typelem", ColType::Int4),     // element type of an array, else 0
            ("typarray", ColType::Int4),    // the array type over this type, else 0
            ("typrelid", ColType::Int4),    // 0 unless a composite type
            ("typtypmod", ColType::Int4),
            ("typnotnull", ColType::Bool),
            ("typdefault", ColType::Text),
            ("typinput", ColType::Text),
            ("typoutput", ColType::Text),
            (
                "typacl",
                ColType::Array(crate::sql::types::ArrElem::AclItem),
            ),
            ("tableoid", ColType::Int4),
            ("typowner", ColType::Int4),
            ("typisdefined", ColType::Bool),
            ("typstorage", ColType::Bpchar),
            ("typdefaultbin", ColType::Text),
        ],
        (false, "pg_namespace") => &[
            ("tableoid", ColType::Int4),
            ("oid", ColType::Int4),
            ("nspname", ColType::Text),
            ("nspowner", ColType::Int4),
            (
                "nspacl",
                ColType::Array(crate::sql::types::ArrElem::AclItem),
            ),
        ],
        (false, "pg_indexes") => &[
            ("schemaname", ColType::Text),
            ("tablename", ColType::Text),
            ("indexname", ColType::Text),
            ("tablespace", ColType::Text),
            ("indexdef", ColType::Text),
        ],
        (false, "pg_tables") => &[
            ("schemaname", ColType::Text),
            ("tablename", ColType::Text),
            ("tableowner", ColType::Text),
            ("tablespace", ColType::Text),
            ("hasindexes", ColType::Bool),
            ("hasrules", ColType::Bool),
            ("hastriggers", ColType::Bool),
            ("rowsecurity", ColType::Bool),
        ],
        (false, "pg_group") => &[
            ("groname", ColType::Name),
            ("grosysid", ColType::Oid),
            ("grolist", ColType::Array(crate::sql::types::ArrElem::Oid)),
        ],
        (false, "pg_shadow" | "pg_user") => &[
            ("usename", ColType::Name),
            ("usesysid", ColType::Oid),
            ("usecreatedb", ColType::Bool),
            ("usesuper", ColType::Bool),
            ("userepl", ColType::Bool),
            ("usebypassrls", ColType::Bool),
            ("passwd", ColType::Text),
            ("valuntil", ColType::Timestamptz),
            (
                "useconfig",
                ColType::Array(crate::sql::types::ArrElem::Text),
            ),
        ],
        (false, "pg_roles") => &[
            ("oid", ColType::Int4),
            ("rolname", ColType::Name),
            ("rolsuper", ColType::Bool),
            ("rolinherit", ColType::Bool),
            ("rolcreaterole", ColType::Bool),
            ("rolcreatedb", ColType::Bool),
            ("rolcanlogin", ColType::Bool),
            ("rolconnlimit", ColType::Int4),
            ("rolpassword", ColType::Text),
            ("rolvaliduntil", ColType::Timestamptz),
            ("rolreplication", ColType::Bool),
            ("rolbypassrls", ColType::Bool),
        ],
        (false, "pg_authid") => &[
            ("oid", ColType::Int4),
            ("rolname", ColType::Name),
            ("rolsuper", ColType::Bool),
            ("rolinherit", ColType::Bool),
            ("rolcreaterole", ColType::Bool),
            ("rolcreatedb", ColType::Bool),
            ("rolcanlogin", ColType::Bool),
            ("rolreplication", ColType::Bool),
            ("rolbypassrls", ColType::Bool),
            ("rolconnlimit", ColType::Int4),
            ("rolpassword", ColType::Text),
            ("rolvaliduntil", ColType::Timestamptz),
        ],
        (false, "pg_auth_members") => &[
            ("oid", ColType::Int4),
            ("roleid", ColType::Int4),
            ("member", ColType::Int4),
            ("grantor", ColType::Int4),
            ("admin_option", ColType::Bool),
            ("inherit_option", ColType::Bool),
            ("set_option", ColType::Bool),
        ],
        (false, "pg_db_role_setting") => &[
            ("setdatabase", ColType::Int4),
            ("setrole", ColType::Int4),
            (
                "setconfig",
                ColType::Array(crate::sql::types::ArrElem::Text),
            ),
        ],
        (false, "pg_database") => &[
            ("oid", ColType::Int4),
            ("datname", ColType::Name),
            ("datdba", ColType::Int4),
            ("encoding", ColType::Int4),
            ("datlocprovider", ColType::Bpchar),
            ("datistemplate", ColType::Bool),
            ("datallowconn", ColType::Bool),
            ("dathasloginevt", ColType::Bool),
            ("datconnlimit", ColType::Int4),
            ("datfrozenxid", ColType::Int4),
            ("datminmxid", ColType::Int4),
            ("dattablespace", ColType::Int4),
            ("datcollate", ColType::Text),
            ("datctype", ColType::Text),
            ("datlocale", ColType::Text),
            ("daticurules", ColType::Text),
            ("datcollversion", ColType::Text),
            (
                "datacl",
                ColType::Array(crate::sql::types::ArrElem::AclItem),
            ),
        ],
        (false, "pg_settings") => &[
            ("name", ColType::Text),
            ("setting", ColType::Text),
            ("unit", ColType::Text),
            ("category", ColType::Text),
            ("short_desc", ColType::Text),
            ("extra_desc", ColType::Text),
            ("context", ColType::Text),
            ("vartype", ColType::Text),
            ("source", ColType::Text),
            ("min_val", ColType::Text),
            ("max_val", ColType::Text),
            ("enumvals", ColType::Array(crate::sql::types::ArrElem::Text)),
            ("boot_val", ColType::Text),
            ("reset_val", ColType::Text),
            ("sourcefile", ColType::Text),
            ("sourceline", ColType::Int4),
            ("pending_restart", ColType::Bool),
        ],
        (false, "pg_prepared_xacts") => &[
            ("transaction", ColType::Xid),
            ("gid", ColType::Text),
            ("prepared", ColType::Timestamptz),
            ("owner", ColType::Name),
            ("database", ColType::Name),
        ],
        (false, "pg_views") => &[
            ("schemaname", ColType::Name),
            ("viewname", ColType::Name),
            ("viewowner", ColType::Name),
            ("definition", ColType::Text),
        ],
        (false, "pg_rules") => &[
            ("schemaname", ColType::Name),
            ("tablename", ColType::Name),
            ("rulename", ColType::Name),
            ("definition", ColType::Text),
        ],
        (false, "pg_matviews") => &[
            ("schemaname", ColType::Name),
            ("matviewname", ColType::Name),
            ("matviewowner", ColType::Name),
            ("tablespace", ColType::Name),
            ("hasindexes", ColType::Bool),
            ("ispopulated", ColType::Bool),
            ("definition", ColType::Text),
        ],
        (false, "pg_sequences") => &[
            ("schemaname", ColType::Text),
            ("sequencename", ColType::Text),
            ("sequenceowner", ColType::Text),
            ("data_type", ColType::Text),
            ("start_value", ColType::Int8),
            ("min_value", ColType::Int8),
            ("max_value", ColType::Int8),
            ("increment_by", ColType::Int8),
            ("cycle", ColType::Bool),
            ("cache_size", ColType::Int8),
            ("last_value", ColType::Int8),
        ],
        (false, "pg_sequence") => &[
            ("seqrelid", ColType::Int4),
            ("seqtypid", ColType::Int4),
            ("seqstart", ColType::Int8),
            ("seqincrement", ColType::Int8),
            ("seqmax", ColType::Int8),
            ("seqmin", ColType::Int8),
            ("seqcache", ColType::Int8),
            ("seqcycle", ColType::Bool),
        ],
        (true, "foreign_data_wrappers") => &[
            ("foreign_data_wrapper_catalog", ColType::Text),
            ("foreign_data_wrapper_name", ColType::Text),
            ("authorization_identifier", ColType::Text),
            ("library_name", ColType::Text),
            ("foreign_data_wrapper_language", ColType::Text),
        ],
        (true, "foreign_data_wrapper_options") => &[
            ("foreign_data_wrapper_catalog", ColType::Text),
            ("foreign_data_wrapper_name", ColType::Text),
            ("option_name", ColType::Text),
            ("option_value", ColType::Text),
        ],
        (true, "foreign_servers") => &[
            ("foreign_server_catalog", ColType::Text),
            ("foreign_server_name", ColType::Text),
            ("foreign_data_wrapper_catalog", ColType::Text),
            ("foreign_data_wrapper_name", ColType::Text),
            ("foreign_server_type", ColType::Text),
            ("foreign_server_version", ColType::Text),
            ("authorization_identifier", ColType::Text),
        ],
        (true, "foreign_server_options") => &[
            ("foreign_server_catalog", ColType::Text),
            ("foreign_server_name", ColType::Text),
            ("option_name", ColType::Text),
            ("option_value", ColType::Text),
        ],
        (true, "foreign_tables") => &[
            ("foreign_table_catalog", ColType::Text),
            ("foreign_table_schema", ColType::Text),
            ("foreign_table_name", ColType::Text),
            ("foreign_server_catalog", ColType::Text),
            ("foreign_server_name", ColType::Text),
        ],
        (true, "foreign_table_options") => &[
            ("foreign_table_catalog", ColType::Text),
            ("foreign_table_schema", ColType::Text),
            ("foreign_table_name", ColType::Text),
            ("option_name", ColType::Text),
            ("option_value", ColType::Text),
        ],
        (true, "column_options") => &[
            ("table_catalog", ColType::Text),
            ("table_schema", ColType::Text),
            ("table_name", ColType::Text),
            ("column_name", ColType::Text),
            ("option_name", ColType::Text),
            ("option_value", ColType::Text),
        ],
        (true, "user_mappings") => &[
            ("authorization_identifier", ColType::Text),
            ("foreign_server_catalog", ColType::Text),
            ("foreign_server_name", ColType::Text),
        ],
        (true, "user_mapping_options") => &[
            ("authorization_identifier", ColType::Text),
            ("foreign_server_catalog", ColType::Text),
            ("foreign_server_name", ColType::Text),
            ("option_name", ColType::Text),
            ("option_value", ColType::Text),
        ],
        (true, "tables") => &[
            ("table_catalog", ColType::Text),
            ("table_schema", ColType::Text),
            ("table_name", ColType::Text),
            ("table_type", ColType::Text),
        ],
        (true, "routines") => &[
            ("specific_catalog", ColType::Text),
            ("specific_schema", ColType::Text),
            ("specific_name", ColType::Text),
            ("routine_catalog", ColType::Text),
            ("routine_schema", ColType::Text),
            ("routine_name", ColType::Text),
            ("routine_type", ColType::Text),
            ("data_type", ColType::Text),
            ("external_language", ColType::Text),
            ("routine_definition", ColType::Text),
        ],
        (true, "routine_privileges" | "role_routine_grants") => &[
            ("grantor", ColType::Text),
            ("grantee", ColType::Text),
            ("specific_catalog", ColType::Text),
            ("specific_schema", ColType::Text),
            ("specific_name", ColType::Text),
            ("routine_catalog", ColType::Text),
            ("routine_schema", ColType::Text),
            ("routine_name", ColType::Text),
            ("privilege_type", ColType::Text),
            ("is_grantable", ColType::Text),
        ],
        (true, "parameters") => &[
            ("specific_catalog", ColType::Text),
            ("specific_schema", ColType::Text),
            ("specific_name", ColType::Text),
            ("ordinal_position", ColType::Int4),
            ("parameter_mode", ColType::Text),
            ("parameter_name", ColType::Text),
            ("data_type", ColType::Text),
            ("udt_catalog", ColType::Text),
            ("udt_schema", ColType::Text),
            ("udt_name", ColType::Text),
        ],
        (true, "views") => &[
            ("table_catalog", ColType::Text),
            ("table_schema", ColType::Text),
            ("table_name", ColType::Text),
            ("view_definition", ColType::Text),
            ("check_option", ColType::Text),
            ("is_updatable", ColType::Text),
            ("is_insertable_into", ColType::Text),
            ("is_trigger_updatable", ColType::Text),
            ("is_trigger_deletable", ColType::Text),
            ("is_trigger_insertable_into", ColType::Text),
        ],
        (true, "view_table_usage") => &[
            ("view_catalog", ColType::Text),
            ("view_schema", ColType::Text),
            ("view_name", ColType::Text),
            ("table_catalog", ColType::Text),
            ("table_schema", ColType::Text),
            ("table_name", ColType::Text),
        ],
        (true, "view_column_usage") => &[
            ("view_catalog", ColType::Text),
            ("view_schema", ColType::Text),
            ("view_name", ColType::Text),
            ("table_catalog", ColType::Text),
            ("table_schema", ColType::Text),
            ("table_name", ColType::Text),
            ("column_name", ColType::Text),
        ],
        (true, "columns") => &[
            ("table_catalog", ColType::Text),
            ("table_schema", ColType::Text),
            ("table_name", ColType::Text),
            ("column_name", ColType::Text),
            ("ordinal_position", ColType::Int4),
            ("column_default", ColType::Text),
            ("is_nullable", ColType::Text),
            ("data_type", ColType::Text),
            ("character_maximum_length", ColType::Int4),
            ("character_octet_length", ColType::Int4),
            ("numeric_precision", ColType::Int4),
            ("numeric_precision_radix", ColType::Int4),
            ("numeric_scale", ColType::Int4),
            ("datetime_precision", ColType::Int4),
            ("interval_type", ColType::Text),
            ("interval_precision", ColType::Int4),
            ("character_set_catalog", ColType::Text),
            ("character_set_schema", ColType::Text),
            ("character_set_name", ColType::Text),
            ("collation_catalog", ColType::Text),
            ("collation_schema", ColType::Text),
            ("collation_name", ColType::Text),
            ("domain_catalog", ColType::Text),
            ("domain_schema", ColType::Text),
            ("domain_name", ColType::Text),
            ("udt_catalog", ColType::Text),
            ("udt_schema", ColType::Text),
            ("udt_name", ColType::Text),
            ("scope_catalog", ColType::Text),
            ("scope_schema", ColType::Text),
            ("scope_name", ColType::Text),
            ("maximum_cardinality", ColType::Int4),
            ("dtd_identifier", ColType::Text),
            ("is_self_referencing", ColType::Text),
            ("is_identity", ColType::Text),
            ("identity_generation", ColType::Text),
            ("identity_start", ColType::Text),
            ("identity_increment", ColType::Text),
            ("identity_maximum", ColType::Text),
            ("identity_minimum", ColType::Text),
            ("identity_cycle", ColType::Text),
            ("is_generated", ColType::Text),
            ("generation_expression", ColType::Text),
            ("is_updatable", ColType::Text),
        ],
        (true, "table_constraints") => &[
            ("constraint_catalog", ColType::Text),
            ("constraint_schema", ColType::Text),
            ("constraint_name", ColType::Text),
            ("table_catalog", ColType::Text),
            ("table_schema", ColType::Text),
            ("table_name", ColType::Text),
            ("constraint_type", ColType::Text),
            ("is_deferrable", ColType::Text),
            ("initially_deferred", ColType::Text),
            ("enforced", ColType::Text),
            ("nulls_distinct", ColType::Text),
        ],
        (true, "key_column_usage") => &[
            ("constraint_catalog", ColType::Text),
            ("constraint_schema", ColType::Text),
            ("constraint_name", ColType::Text),
            ("table_catalog", ColType::Text),
            ("table_schema", ColType::Text),
            ("table_name", ColType::Text),
            ("column_name", ColType::Text),
            ("ordinal_position", ColType::Int4),
            ("position_in_unique_constraint", ColType::Int4),
        ],
        (true, "constraint_column_usage") => &[
            ("table_catalog", ColType::Text),
            ("table_schema", ColType::Text),
            ("table_name", ColType::Text),
            ("column_name", ColType::Text),
            ("constraint_catalog", ColType::Text),
            ("constraint_schema", ColType::Text),
            ("constraint_name", ColType::Text),
        ],
        (true, "sequences") => &[
            ("sequence_catalog", ColType::Text),
            ("sequence_schema", ColType::Text),
            ("sequence_name", ColType::Text),
            ("data_type", ColType::Text),
            ("numeric_precision", ColType::Int4),
            ("numeric_precision_radix", ColType::Int4),
            ("numeric_scale", ColType::Int4),
            ("start_value", ColType::Text),
            ("minimum_value", ColType::Text),
            ("maximum_value", ColType::Text),
            ("increment", ColType::Text),
            ("cycle_option", ColType::Text),
        ],
        (true, "usage_privileges") => &[
            ("grantor", ColType::Text),
            ("grantee", ColType::Text),
            ("object_catalog", ColType::Text),
            ("object_schema", ColType::Text),
            ("object_name", ColType::Text),
            ("object_type", ColType::Text),
            ("privilege_type", ColType::Text),
            ("is_grantable", ColType::Text),
        ],
        (true, "table_privileges" | "role_table_grants") => &[
            ("grantor", ColType::Text),
            ("grantee", ColType::Text),
            ("table_catalog", ColType::Text),
            ("table_schema", ColType::Text),
            ("table_name", ColType::Text),
            ("privilege_type", ColType::Text),
            ("is_grantable", ColType::Text),
            ("with_hierarchy", ColType::Text),
        ],
        (true, "column_privileges" | "role_column_grants") => &[
            ("grantor", ColType::Text),
            ("grantee", ColType::Text),
            ("table_catalog", ColType::Text),
            ("table_schema", ColType::Text),
            ("table_name", ColType::Text),
            ("column_name", ColType::Text),
            ("privilege_type", ColType::Text),
            ("is_grantable", ColType::Text),
        ],
        (true, "referential_constraints") => &[
            ("constraint_catalog", ColType::Text),
            ("constraint_schema", ColType::Text),
            ("constraint_name", ColType::Text),
            ("unique_constraint_catalog", ColType::Text),
            ("unique_constraint_schema", ColType::Text),
            ("unique_constraint_name", ColType::Text),
            ("match_option", ColType::Text),
            ("update_rule", ColType::Text),
            ("delete_rule", ColType::Text),
        ],
        (true, "domains") => &[
            ("domain_catalog", ColType::Text),
            ("domain_schema", ColType::Text),
            ("domain_name", ColType::Text),
            ("data_type", ColType::Text),
            ("character_maximum_length", ColType::Int4),
            ("character_octet_length", ColType::Int4),
            ("character_set_catalog", ColType::Text),
            ("character_set_schema", ColType::Text),
            ("character_set_name", ColType::Text),
            ("collation_catalog", ColType::Text),
            ("collation_schema", ColType::Text),
            ("collation_name", ColType::Text),
            ("numeric_precision", ColType::Int4),
            ("numeric_precision_radix", ColType::Int4),
            ("numeric_scale", ColType::Int4),
            ("datetime_precision", ColType::Int4),
            ("interval_type", ColType::Text),
            ("interval_precision", ColType::Int4),
            ("domain_default", ColType::Text),
            ("udt_catalog", ColType::Text),
            ("udt_schema", ColType::Text),
            ("udt_name", ColType::Text),
            ("scope_catalog", ColType::Text),
            ("scope_schema", ColType::Text),
            ("scope_name", ColType::Text),
            ("maximum_cardinality", ColType::Int4),
            ("dtd_identifier", ColType::Text),
        ],
        (true, "domain_constraints") => &[
            ("constraint_catalog", ColType::Text),
            ("constraint_schema", ColType::Text),
            ("constraint_name", ColType::Text),
            ("domain_catalog", ColType::Text),
            ("domain_schema", ColType::Text),
            ("domain_name", ColType::Text),
            ("is_deferrable", ColType::Text),
            ("initially_deferred", ColType::Text),
        ],
        (true, "check_constraints") => &[
            ("constraint_catalog", ColType::Text),
            ("constraint_schema", ColType::Text),
            ("constraint_name", ColType::Text),
            ("check_clause", ColType::Text),
        ],
        (true, "column_domain_usage") => &[
            ("domain_catalog", ColType::Text),
            ("domain_schema", ColType::Text),
            ("domain_name", ColType::Text),
            ("table_catalog", ColType::Text),
            ("table_schema", ColType::Text),
            ("table_name", ColType::Text),
            ("column_name", ColType::Text),
        ],
        (true, "column_udt_usage") => &[
            ("udt_catalog", ColType::Text),
            ("udt_schema", ColType::Text),
            ("udt_name", ColType::Text),
            ("table_catalog", ColType::Text),
            ("table_schema", ColType::Text),
            ("table_name", ColType::Text),
            ("column_name", ColType::Text),
        ],
        (true, "domain_udt_usage") => &[
            ("udt_catalog", ColType::Text),
            ("udt_schema", ColType::Text),
            ("udt_name", ColType::Text),
            ("domain_catalog", ColType::Text),
            ("domain_schema", ColType::Text),
            ("domain_name", ColType::Text),
        ],
        (true, "schemata") => &[
            ("catalog_name", ColType::Text),
            ("schema_name", ColType::Text),
            ("schema_owner", ColType::Text),
            ("default_character_set_catalog", ColType::Text),
            ("default_character_set_schema", ColType::Text),
            ("default_character_set_name", ColType::Text),
            ("sql_path", ColType::Text),
        ],
        (true, "collations") => &[
            ("collation_catalog", ColType::Text),
            ("collation_schema", ColType::Text),
            ("collation_name", ColType::Text),
            ("pad_attribute", ColType::Text),
        ],
        (true, "collation_character_set_applicability") => &[
            ("collation_catalog", ColType::Text),
            ("collation_schema", ColType::Text),
            ("collation_name", ColType::Text),
            ("character_set_catalog", ColType::Text),
            ("character_set_schema", ColType::Text),
            ("character_set_name", ColType::Text),
        ],
        (true, "enabled_roles") => &[("role_name", ColType::Text)],
        (true, "administrable_role_authorizations" | "applicable_roles") => &[
            ("grantee", ColType::Text),
            ("role_name", ColType::Text),
            ("is_grantable", ColType::Text),
        ],
        (false, "pg_seclabel") => &[
            ("objoid", ColType::Oid),
            ("classoid", ColType::Oid),
            ("objsubid", ColType::Int4),
            ("provider", ColType::Text),
            ("label", ColType::Text),
        ],
        _ => return None,
    };
    Some(SynthDef { name, columns })
}

pub(super) fn require(name: &str, information_schema: bool) -> SynthDef<'_> {
    definition(name, information_schema).expect("implemented catalog has a schema")
}

pub(super) fn hidden_columns(
    name: &str,
    information_schema: bool,
) -> &'static [(&'static str, ColType)] {
    match (information_schema, name) {
        (false, "pg_class" | "pg_constraint" | "pg_attrdef") => &[("tableoid", ColType::Oid)],
        _ => &[],
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_exposed_catalog_has_a_bounded_shared_definition() {
        let bytes = core::mem::size_of::<crate::storage::TableDef>();
        let mut budget = crate::mem::budget::Budget::new(bytes);
        let arena =
            crate::mem::arena::Arena::new(&mut budget, "schema definition only", bytes).unwrap();
        for name in super::super::CATALOG_RELATIONS {
            let definition =
                definition(name, false).expect("exposed PostgreSQL catalog has a schema");
            assert_eq!(definition.name, *name);
            assert!(
                definition.columns.len() + hidden_columns(name, false).len()
                    <= crate::storage::MAX_COLUMNS
            );
            let mark = arena.mark();
            crate::mem::guard::forbid_alloc(|| {
                let table =
                    super::super::synthesize_definition(Some("pg_catalog"), name, &arena).unwrap();
                assert_eq!(arena.used(), bytes);
                assert!(table.rows.is_empty());
            });
            // No descriptor from this iteration remains live.
            unsafe { arena.rewind_to(mark) };
        }
        for name in [
            "foreign_data_wrappers",
            "foreign_data_wrapper_options",
            "foreign_servers",
            "foreign_server_options",
            "foreign_tables",
            "foreign_table_options",
            "column_options",
            "user_mappings",
            "user_mapping_options",
            "tables",
            "routines",
            "routine_privileges",
            "role_routine_grants",
            "parameters",
            "views",
            "view_table_usage",
            "view_column_usage",
            "columns",
            "table_constraints",
            "key_column_usage",
            "constraint_column_usage",
            "sequences",
            "usage_privileges",
            "table_privileges",
            "role_table_grants",
            "column_privileges",
            "role_column_grants",
            "referential_constraints",
            "domains",
            "domain_constraints",
            "check_constraints",
            "column_domain_usage",
            "column_udt_usage",
            "domain_udt_usage",
            "schemata",
            "collations",
            "collation_character_set_applicability",
            "enabled_roles",
            "administrable_role_authorizations",
            "applicable_roles",
        ] {
            assert!(super::super::is_catalog_relation(
                Some("information_schema"),
                name
            ));
            let definition =
                definition(name, true).expect("exposed information schema has a schema");
            assert!(definition.columns.len() <= crate::storage::MAX_COLUMNS);
        }
        assert!(definition("not_an_implemented_catalog", false).is_none());
    }
}
