--
-- PostgreSQL database dump
--

\restrict uxYIAPfy7QdtLdbfjO0HUjvS4LDBkYZvlZhNOf3wqYW95t3kWLgw2MQz3fpPy83

-- Dumped from database version 18.4 (Homebrew)
-- Dumped by pg_dump version 18.4 (Homebrew)
--
-- Provenance: generated on 2026-07-28 with vanilla PostgreSQL 18.4
-- (`pg_dump --format=plain --no-owner --no-privileges`) from the schema
-- represented below. The artifact is checked in verbatim except for this
-- provenance paragraph.

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: app; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA app;


--
-- Name: SCHEMA app; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA app IS 'application schema';


--
-- Name: mood; Type: TYPE; Schema: app; Owner: -
--

CREATE TYPE app.mood AS ENUM (
    'sad',
    'ok',
    'happy'
);


--
-- Name: positive; Type: DOMAIN; Schema: app; Owner: -
--

CREATE DOMAIN app.positive AS integer
	CONSTRAINT positive_check CHECK ((VALUE > 0));


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: entry; Type: TABLE; Schema: app; Owner: -
--

CREATE TABLE app.entry (
    id bigint NOT NULL,
    parent_id integer,
    state app.mood DEFAULT 'ok'::app.mood NOT NULL,
    states app.mood[] DEFAULT ARRAY['sad'::app.mood, 'happy'::app.mood],
    amount app.positive DEFAULT 1,
    note character varying(40),
    doubled integer GENERATED ALWAYS AS (((amount)::integer * 2)) STORED,
    created_at timestamp with time zone DEFAULT now(),
    payload jsonb DEFAULT '{"ready": true}'::jsonb,
    tags text[] DEFAULT ARRAY[]::text[],
    CONSTRAINT entry_note_check CHECK (((note IS NULL) OR (length((note)::text) > 1)))
);


--
-- Name: TABLE entry; Type: COMMENT; Schema: app; Owner: -
--

COMMENT ON TABLE app.entry IS 'dumped entries';


--
-- Name: COLUMN entry.note; Type: COMMENT; Schema: app; Owner: -
--

COMMENT ON COLUMN app.entry.note IS 'optional note';


--
-- Name: entry_counts; Type: MATERIALIZED VIEW; Schema: app; Owner: -
--

CREATE MATERIALIZED VIEW app.entry_counts AS
 SELECT state,
    count(*) AS n
   FROM app.entry
  GROUP BY state
  WITH NO DATA;


--
-- Name: entry_id_seq; Type: SEQUENCE; Schema: app; Owner: -
--

ALTER TABLE app.entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME app.entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: entry_view; Type: VIEW; Schema: app; Owner: -
--

CREATE VIEW app.entry_view AS
 SELECT id,
    state,
    note
   FROM app.entry
  WHERE ((amount)::integer > 0);


--
-- Name: parent; Type: TABLE; Schema: app; Owner: -
--

CREATE TABLE app.parent (
    id integer NOT NULL,
    label text NOT NULL
);


--
-- Name: parent_id_seq; Type: SEQUENCE; Schema: app; Owner: -
--

ALTER TABLE app.parent ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME app.parent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ticket_seq; Type: SEQUENCE; Schema: app; Owner: -
--

CREATE SEQUENCE app.ticket_seq
    START WITH 10
    INCREMENT BY 5
    MINVALUE 10
    MAXVALUE 1000
    CACHE 3;


--
-- Data for Name: entry; Type: TABLE DATA; Schema: app; Owner: -
--

COPY app.entry (id, parent_id, state, states, amount, note, created_at, payload, tags) FROM stdin;
1	1	happy	{sad,happy}	3	alpha	2026-07-28 08:26:44.014171+00	{"ready": true}	{x,y}
2	2	sad	{sad,happy}	5	\N	2026-07-28 08:26:44.014171+00	{"ready": true}	{}
\.


--
-- Data for Name: parent; Type: TABLE DATA; Schema: app; Owner: -
--

COPY app.parent (id, label) FROM stdin;
1	one
2	two
\.


--
-- Name: entry_id_seq; Type: SEQUENCE SET; Schema: app; Owner: -
--

SELECT pg_catalog.setval('app.entry_id_seq', 2, true);


--
-- Name: parent_id_seq; Type: SEQUENCE SET; Schema: app; Owner: -
--

SELECT pg_catalog.setval('app.parent_id_seq', 2, true);


--
-- Name: ticket_seq; Type: SEQUENCE SET; Schema: app; Owner: -
--

SELECT pg_catalog.setval('app.ticket_seq', 25, true);


--
-- Name: entry entry_parent_state_key; Type: CONSTRAINT; Schema: app; Owner: -
--

ALTER TABLE ONLY app.entry
    ADD CONSTRAINT entry_parent_state_key UNIQUE (parent_id, state);


--
-- Name: entry entry_pkey; Type: CONSTRAINT; Schema: app; Owner: -
--

ALTER TABLE ONLY app.entry
    ADD CONSTRAINT entry_pkey PRIMARY KEY (id);


--
-- Name: parent parent_label_key; Type: CONSTRAINT; Schema: app; Owner: -
--

ALTER TABLE ONLY app.parent
    ADD CONSTRAINT parent_label_key UNIQUE (label);


--
-- Name: parent parent_pkey; Type: CONSTRAINT; Schema: app; Owner: -
--

ALTER TABLE ONLY app.parent
    ADD CONSTRAINT parent_pkey PRIMARY KEY (id);


--
-- Name: entry_note_idx; Type: INDEX; Schema: app; Owner: -
--

CREATE INDEX entry_note_idx ON app.entry USING btree (note);


--
-- Name: entry entry_parent_id_fkey; Type: FK CONSTRAINT; Schema: app; Owner: -
--

ALTER TABLE ONLY app.entry
    ADD CONSTRAINT entry_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES app.parent(id) ON DELETE CASCADE;


--
-- Name: entry_counts; Type: MATERIALIZED VIEW DATA; Schema: app; Owner: -
--

REFRESH MATERIALIZED VIEW app.entry_counts;


--
-- PostgreSQL database dump complete
--

\unrestrict uxYIAPfy7QdtLdbfjO0HUjvS4LDBkYZvlZhNOf3wqYW95t3kWLgw2MQz3fpPy83
