#!/bin/sh
set -eu

# Regenerate the built-in relation/attribute identities from an unmodified
# PostgreSQL 18 server. The container name may be overridden for local use.
container=${PG18_CONTAINER:-pos3ql-pg18-ref}
output=${1:-src/sql/catalog_metadata.rs}

{
    printf '%s\n' '// Generated by tools/generate-pg18-catalog-metadata.sh from PostgreSQL 18.'
    printf '%s\n' '// Do not edit by hand.'
    printf '%s\n\n' 'use super::types::Datum;'
    printf '%s\n' '#[derive(Clone, Copy)]'
    printf '%s\n' 'pub(crate) struct CatalogRelation {'
    printf '%s\n' "    pub(crate) name: &'static str,"
    printf '%s\n' '    pub(crate) oid: i32,'
    printf '%s\n' '    pub(crate) row_type_oid: i32,'
    printf '%s\n' "    pub(crate) kind: &'static str,"
    printf '%s\n' '    pub(crate) attributes: i32,'
    printf '%s\n' '    pub(crate) access_method: i32,'
    printf '%s\n' '    pub(crate) has_index: bool,'
    printf '%s\n' '    pub(crate) has_rules: bool,'
    printf '%s\n' '}'
    printf '%s\n' '#[rustfmt::skip]'
    printf '%s\n\n' 'pub(crate) const RELATIONS: &[CatalogRelation] = &['
    docker exec "$container" psql -U postgres -Atc "
        SELECT format(
            '    CatalogRelation { name: %s, oid: %s, row_type_oid: %s, kind: %s, attributes: %s, access_method: %s, has_index: %s, has_rules: %s },',
            chr(34) || c.relname || chr(34), c.oid, c.reltype,
            chr(34) || c.relkind::text || chr(34), c.relnatts, c.relam,
            CASE WHEN c.relhasindex THEN 'true' ELSE 'false' END,
            CASE WHEN c.relhasrules THEN 'true' ELSE 'false' END)
        FROM pg_catalog.pg_class AS c
        WHERE c.relnamespace = 'pg_catalog'::regnamespace
          AND c.relkind IN ('r', 'v', 'm', 'p', 'S')
        ORDER BY c.oid;"
    printf '%s\n\n' '];'
    printf '%s\n' '#[rustfmt::skip]'
    printf '%s\n' 'pub(crate) const TIMEZONE_ABBREVIATIONS: &[(&str, i32, bool)] = &['
    docker exec "$container" psql -U postgres -Atc "
        SELECT format(
            '    (%s, %s, %s),',
            chr(34) || abbrev || chr(34),
            extract(epoch FROM utc_offset)::integer,
            CASE WHEN is_dst THEN 'true' ELSE 'false' END)
        FROM pg_catalog.pg_timezone_abbrevs
        ORDER BY abbrev;"
    printf '%s\n\n' '];'
    printf '%s\n' '#[rustfmt::skip]'
    printf '%s\n' 'pub(crate) const ATTRIBUTE_ROWS: &[[Datum<'"'"'static>; 25]] = &['
    docker exec "$container" psql -U postgres -Atc "
        SELECT format(
            '    [Datum::Oid(%s), Datum::Text(%s), Datum::Oid(%s), Datum::Int2(%s), Datum::Int2(%s), Datum::Int4(%s), Datum::Int2(%s), Datum::Bool(%s), Datum::Char(%s), Datum::Char(%s), Datum::Char(%s), Datum::Bool(%s), Datum::Bool(%s), Datum::Bool(%s), Datum::Char(%s), Datum::Char(%s), Datum::Bool(%s), Datum::Bool(%s), Datum::Int2(%s), Datum::Oid(%s), %s, Datum::Null, Datum::Null, Datum::Null, Datum::Null],',
            a.attrelid, chr(34) || a.attname || chr(34), a.atttypid, a.attlen,
            a.attnum, a.atttypmod, a.attndims,
            CASE WHEN t.typbyval THEN 'true' ELSE 'false' END,
            ascii(a.attalign), ascii(a.attstorage),
            CASE WHEN a.attcompression = '' THEN 0 ELSE ascii(a.attcompression) END,
            CASE WHEN a.attnotnull THEN 'true' ELSE 'false' END,
            CASE WHEN a.atthasdef THEN 'true' ELSE 'false' END,
            CASE WHEN a.atthasmissing THEN 'true' ELSE 'false' END,
            CASE WHEN a.attidentity = '' THEN 0 ELSE ascii(a.attidentity) END,
            CASE WHEN a.attgenerated = '' THEN 0 ELSE ascii(a.attgenerated) END,
            CASE WHEN a.attisdropped THEN 'true' ELSE 'false' END,
            CASE WHEN a.attislocal THEN 'true' ELSE 'false' END,
            a.attinhcount, a.attcollation,
            CASE WHEN a.attstattarget IS NULL OR a.attstattarget = -1 THEN 'Datum::Null' ELSE 'Datum::Int2(' || a.attstattarget || ')' END)
        FROM pg_catalog.pg_attribute AS a
        JOIN pg_catalog.pg_class AS c ON c.oid = a.attrelid
        JOIN pg_catalog.pg_type AS t ON t.oid = a.atttypid
        WHERE c.relnamespace = 'pg_catalog'::regnamespace
          AND c.relkind IN ('r', 'v', 'm', 'p', 'S')
          AND a.attnum > 0
          AND NOT a.attisdropped
        ORDER BY a.attrelid, a.attnum;"
    printf '%s\n' '];'
} > "$output"

rustfmt "$output"
